[package]
name = "dtftools"
version = "0.3.0"
edition = "2018"

[dependencies]
libtectonic = { path = "../libtectonic", version = "0.3.0" }
clap = "2.33.0"
serde = "1.0.103"
serde_derive = "1.0.103"
serde_json = "1.0.42"
byteorder = "1.3.2"
indoc = "0.3.4"
