#!/bin/sh
tmux new-session -d 'cargo run --release --bin tdb-server -- -vv; bash'
tmux split-window -v 'cargo run --release --bin tdb; bash'
tmux split-window -h 'cd ../bookkeeper; BITFINEX_ENABLED=1 BINANCE_ENABLED=1 cargo run --release --bin ingestor; bash'
tmux new-window 'mutt'
tmux -2 attach-session -d

