[package]
name = "gen_train_data"
version = "0.3.0"
edition = "2018"

[dependencies]
libtectonic = { path = "../libtectonic", version = "0.3.0" }
clap = "2.33.0"
byteorder = "1.3.2"
fern = "0.5.8"
chrono = "0.4.9"