[package]
name = "dtfconcat"
version = "0.3.0"
edition = "2018"

[dependencies]
libtectonic = { path = "../lib", version = "0.3.0" }
clap = "2.33.0"
serde = "1.0.101"
serde_derive = "1.0.101"
serde_json = "1.0.41"
byteorder = "1.3.2"